

export const APP_FEATURES = [
    {
        id: '01',
        title: 'tailored just for you',
        description:
        'get interview questions and model answers based on your role, experience, and specific focus areas '
    },
    {
        id: '02',
        title: 'learn at your own pace',
        description:
        'expand answers only when you are ready.'
    },
    {
        id: '03',
        title: 'capture your insights',
        description:
        'add personal notes to any questions and pin important ones to the top.'
    },
    {
        id: '04',
        title: 'understand the why behind answers',
        description:
        'beyond just anwers- wnlock detailed concept explanations generated by AI.'
    },
    {
        id: '05',
        title: 'save, organize, and revisit',
        description:
        'easily save your interview sets, organize them neatly in your dashboard.'
    },
]